environment: production

paths:
  config: ~/.quantumspectre/config.yml
  data_dir: ~/.quantumspectre/data
  log_dir: ~/.quantumspectre/logs
  model_dir: ~/.quantumspectre/models

services:
  enabled:
    - data_ingest
    - data_feed
    - feature_service
    - intelligence
    - ml_model
    - strategy_brain
    - brain_council
    - execution_engine
    - risk_manager
    - backtester
    - monitoring
    - api_gateway
    - ui_server

database:
  host: localhost
  port: 5432
  user: spectre
  password: securepassword
  dbname: quantumspectre
  min_pool_size: 5
  max_pool_size: 20
  connection_timeout: 60
  command_timeout: 60

api:
  rate_limit:
    default: 100
    trading: 20
    auth: 10

http:
  timeout_default: 10
  timeout_feed: 30
  timeout_long: 120
  retries: 3
  backoff: 2.0

websocket:
  max_connections: 10000
  ping_interval: 30
  ping_timeout: 10
  close_timeout: 5

auth:
  token_expiry_access: 3600
  token_expiry_refresh: 2592000
  password_min_length: 10
  hash_algorithm: pbkdf2_sha256
  salt_length: 32
  hash_iterations: 200000

cache:
  default_ttl: 300
  long_ttl: 3600
  very_long_ttl: 86400

resources:
  thread_pool_size: 10
  max_thread_pool_size: 100
  process_pool_size: 4
  max_process_pool_size: 16
  memory_warning_threshold: 0.85
  memory_critical_threshold: 0.95

logging:
  level: INFO
  ui_level: info

ui:
  theme: dark
  chart_type: candlestick
  default_timeframe: 1h
  default_exchange: binance
  default_layout: trading_focus
  auto_refresh_interval: 5
  sound_alerts: true
  voice_assistant: true
  hotkeys_enabled: false
  confirm_orders: true
